# Numpy Library

In Python, primarily within the context of libraries like NumPy and Pandas, the ndim attribute refers to the total number of dimensions (axes) in an array, while the shape attribute returns a tuple detailing the size or length of each individual dimension.

In [2]:
import numpy as np

In [2]:
x_4d = np.array([
    [
     [[1], [2]],
     [[3], [4]],
     [[5], [6]]
    ],

    [[[7], [8]], [[9], [10]], [[11], [12]]],
    
    [[[13], [14]], [[15], [16]], [[17], [18]]],
    
    [[[19], [20]], [[21], [22]], [[23], [24]]]
])

In [3]:
x_4d.ndim

4

In [4]:
np.ndim(x_4d)

4

In [5]:
x_4d.shape

(4, 3, 2, 1)

In [6]:
np.shape(x_4d)

(4, 3, 2, 1)

In [7]:
x_4d.dtype

dtype('int64')

In [8]:
type(x_4d)

numpy.ndarray

In [9]:
x_3d = np.array([
    [
     [1, 2], 
     [3, 4], 
     [5, 6]
    ], 
    [[7, 8], [9, 10], [11, 12]],
    [[13, 14], [15, 16], [17, 18]],
    [[19, 20], [21, 22], [23, 24]]
])

In [10]:
x_3d.ndim

3

In [11]:
x_3d.shape

(4, 3, 2)

In [12]:
y_3d = np.array([
    [[1], [2]],
    [[3], [4]],
    [[5], [6]],
    [[7], [8]]
], dtype = np.int16)

In [13]:
y_3d.ndim

3

In [14]:
y_3d.shape

(4, 2, 1)

In [15]:
y_3d.dtype

dtype('int16')

In [16]:
y_2d = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
], dtype=np.float32)

In [17]:
y_2d.ndim

2

In [18]:
y_2d.shape

(4, 2)

In [19]:
y_2d.dtype

dtype('float32')

In [20]:
z_2d = np.array([
    [1],
    [2],
    [3]
])

In [21]:
z_2d.ndim

2

In [22]:
z_2d.shape

(3, 1)

In [23]:
z_1d = np.array([
    1, 2, 3
])

In [24]:
z_1d.ndim

1

In [25]:
z_1d.shape

(3,)

## `np.random.randn()` function

The `np.random.randn()` function in Python's NumPy library returns a sample or samples from the **standard normal distribution** (mean 0, variance 1).

- Distribution: Standard Normal or Standard Gaussian
    - Mean: 0
    - Std dev: 1
- Range: (-∞, ∞)
- Arguments: Shape as separate args

In [26]:
# Return a single random float
np.random.randn()

-2.888822974927197

In [27]:
# Return a 1D array of random floats
np.random.randn(5)

array([-2.60423193, -0.08595815,  0.16338373,  0.16985525, -0.84833607])

In [28]:
# Return a 2D array (matrix) of random floats
np.random.randn(3, 4)

array([[-0.07520945,  1.44389766,  1.49105992,  0.45781346],
       [-1.36492885,  1.52846854, -0.19324994, -0.08419916],
       [-0.5642904 , -0.92486529,  0.82012448, -0.06849468]])

In [29]:
# Return a 3D array (tensor) of random floats
np.random.randn(3, 2, 1)

array([[[ 0.81710364],
        [-1.65512466]],

       [[ 0.46675826],
        [-1.86940228]],

       [[ 1.36024088],
        [-0.42058418]]])

In [30]:
sizes = [10, 5, 3]

In [31]:
biases = [np.random.randn(size, 1) for size in sizes[1:]]
biases

[array([[0.59490421],
        [0.53961752],
        [1.69251253],
        [0.74232466],
        [0.28362425]]),
 array([[ 1.438308  ],
        [-0.2908729 ],
        [-1.46481128]])]

In [32]:
sizes = [3, 2, 1]

In [33]:
weights = [np.random.rand(next, curr) for curr, next in zip(sizes[:-1], sizes[1:])]
weights

[array([[0.14619804, 0.16235411, 0.24630469],
        [0.87753401, 0.83668568, 0.4487831 ]]),
 array([[0.4059145 , 0.25066952]])]

## `numpy.random.rand()` Function

`numpy.random.rand()` is a simple way to generate random numbers from a **uniform distribution** over the interval [0, 1).

- Distribution: Uniform
- Range: [0, 1)
- Arguments: Shape as separate args

In [34]:
# Return a single random float between 0 and 1
np.random.rand()

0.545091702248341

In [35]:
# Return a 1D array of random floats between 0 and 1
np.random.rand(5)

array([0.68030064, 0.21871555, 0.45765246, 0.2434238 , 0.76032232])

In [36]:
# Return a 2D array of random floats between 0 and 1
np.random.rand(4, 3)

array([[0.58407396, 0.11873202, 0.98591917],
       [0.35435971, 0.60975881, 0.83292982],
       [0.80532823, 0.12902728, 0.05561515],
       [0.97738461, 0.62239649, 0.12047983]])

In [37]:
# Return a 3D array of random floats between 0 and 1
np.random.rand(3, 2, 1)

array([[[0.83011412],
        [0.99452817]],

       [[0.16985115],
        [0.55758328]],

       [[0.13578557],
        [0.87342579]]])

## Reproducibility (seed)

In [38]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [39]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [40]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

## Dot Product

In [97]:
# Weight Matrix
w = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

In [99]:
# Input Activation vector
a = np.array([
    [1], 
    [2], 
    [3], 
    [4]
])

In [100]:
np.dot(w, a)

array([[30],
       [70]])

In [112]:
# Biases
b = np.array([
    [1],
    [-67]
])

In [113]:
np.dot(w, a) + b

array([[31],
       [ 3]])

## Functions on Numpy arrays

In [134]:
w = np.random.randn(5, 10)

In [135]:
a = np.random.randn(10, 1)

In [136]:
b = np.random.randn(5, 1)

In [137]:
z  = np.dot(w, a) + b

In [138]:
z

array([[-0.05362028],
       [-0.55395221],
       [ 1.43636968],
       [ 8.40140166],
       [ 2.96089833]])

In [139]:
np.exp(-z)

array([[1.05508389e+00],
       [1.74011676e+00],
       [2.37789446e-01],
       [2.24552357e-04],
       [5.17723874e-02]])

In [140]:
1.0 / (1.0 + np.exp(-z))

array([[0.48659814],
       [0.36494795],
       [0.80789185],
       [0.9997755 ],
       [0.95077605]])

## `numpy.reshape()`

`numpy.reshape()` is used to change the shape (dimensions) of an array without changing its data.

- Changes shape (dimensions) of an array
- Does NOT change data
- Total elements remain constant
- Syntax: `numpy.reshape(array, new_shape)` or `array_name.reshape(new_shape)` 

In [5]:
a = np.array([1, 2, 3, 4, 5, 6])

In [6]:
a.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# NumPy can automatically calculate one dimension
a = np.array([1,2,3,4,5,6])
a.reshape((2, -1))

# -1 tells NumPy to figure out the length/size of other axis/dimension

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# Flatten input
a.reshape(-1)

# x.reshape(784, 1)

array([1, 2, 3, 4, 5, 6])

## `numpy.random.shuffle()`

In NumPy, you can randomly shuffle an array using two primary methods: `numpy.random.shuffle()` to modify the array in-place or `numpy.random.permutation()` to return a new shuffled array while leaving the original intact.

The `numpy.random.shuffle()` function modifies the array directly and returns None. For multi-dimensional arrays, it only shuffles along the first axis (rows).

In [3]:
# Use the recommended Generator instance for new code
rng = np.random.default_rng()

In [4]:
arr_1d = np.array([1, 2, 3, 4, 5])
rng.shuffle(arr_1d) # Shuffles the array in-place
print("Shuffled 1D array:", arr_1d)

Shuffled 1D array: [3 2 5 1 4]


In [5]:
arr_2d = np.array([[10, 20], [30, 40], [50, 60]])
rng.shuffle(arr_2d) # Only shuffles the rows (1st axis)
print("Shuffled 2D array (rows only):\n", arr_2d)

Shuffled 2D array (rows only):
 [[30 40]
 [10 20]
 [50 60]]


## `numpy.random.permutation()`

The `numpy.random.permutation()` function returns a new shuffled array (a copy) and keeps the original array unchanged. This is useful when you need to preserve the original data.

In [6]:
# Use the recommended Generator instance for new code
rng = np.random.default_rng()

In [7]:
original_arr = np.array([1, 2, 3, 4, 5])
shuffled_arr = rng.permutation(original_arr)
print("Original array:", original_arr)
print("New shuffled array:", shuffled_arr)

Original array: [1 2 3 4 5]
New shuffled array: [2 3 4 1 5]


In [17]:
arr_2d_org = np.array([[10, 20], [30, 40], [50, 60]])
arr_2d_shuf = rng.permutation(arr_2d_org) # Only shuffles the rows (1st axis)
print("Original array:", arr_2d_org)
print("New shuffled array:", arr_2d_shuf)

Original array: [[10 20]
 [30 40]
 [50 60]]
New shuffled array: [[30 40]
 [10 20]
 [50 60]]


In [20]:
# It can also take an integer N and shuffle np.arange(N)
shuffled_range = rng.permutation(5)
print("Shuffled range(5):", shuffled_range)

Shuffled range(5): [2 4 3 0 1]


## `numpy.arange()`

The `numpy.arange()` function creates an array of evenly spaced values within a specified interval. It is similar to Python's built-in `range()` function but returns a NumPy array (ndarray) and can handle floating-point numbers.

The syntax for `np.arange()` is as follows, with parameters after `stop` being optional: 

`numpy.arange([start,] stop, [step,] dtype=None)`

**Parameters**:
- `start` (optional): The beginning of the interval. The default is 0. The interval includes this value.
- `stop`: The end of the interval. The interval excludes this value (half-open interval [`start`, `stop`)).
- `step` (optional): The spacing between consecutive values. The default step is 1. This can be a negative value to create a descending sequence.
- `dtype` (optional): The data type of the output array elements. If not specified, the data type is inferred from the other arguments. 

**Basic usage (only `stop` provided)**: 

Create an array starting at `0` up to (but not including) `5`, with a default step of `1`.

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

**Specifying `start` and `stop`**: 

Create an array from `2` up to (but not including) `8`.

In [23]:
np.arange(2, 8)

array([2, 3, 4, 5, 6, 7])

**Specifying `start`, `stop`, and `step`**: 

Create an array from `2` up to (but not including) `10`, with a step of `2`.

In [24]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

**Using floating-point numbers**

In [25]:
np.arange(1.0, 5.0, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

## `numpy.zeros()`

The `numpy.zeros()` function creates a new array of a specified shape and data type, with all elements initialized to zero. This function is commonly used for pre-allocating memory for arrays that will be populated with data later.

**Syntax**:

`numpy.zeros(shape, dtype=float64, order='C', like=None)`

- `shape` (required): An integer or a tuple of integers defining the dimensions of the array (e.g., `5` for a 1D array of 5 elements, or (`2`, `3`) for a 2D array with `2` rows and `3` columns).
- `dtype` (optional): The desired data type for the array elements. The default is `numpy.float64`. You can specify `int` to create an array of integers.
- `order` (optional): Specifies the memory layout, either C-style (row-major) or Fortran-style (column-major). The default is 'C'.

In [26]:
# Create a 1D array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
# Create a 2D array (matrix)
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
# Create an array with integer data type
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

## `np.ones()`

`np.ones()` is a NumPy function used to create a new array of a specified shape and data type, filled entirely with ones. It is primarily used for initializing matrices or creating arrays for numerical computations. The default data type is `float64`, but it can be changed to integers or other types using the `dtype` parameter.

**Syntax**: 

`numpy.ones(shape, dtype=None, order='C')`

- `shape`: An integer or tuple of integers defining the dimensions (e.g., `(2, 3)` for a 2x3 matrix).
- `dtype` (Optional): Desired data type (e.g., `int`, `bool`, `float`).
- `order` (Optional): 'C' for row-major or 'F' for column-major storage.

In [30]:
# Create a 1D array of 5 ones (floats)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
# Create a 2D array (matrix) of 3x2 ones (integers)
np.ones((3, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])