# Numpy Library

In Python, primarily within the context of libraries like NumPy and Pandas, the ndim attribute refers to the total number of dimensions (axes) in an array, while the shape attribute returns a tuple detailing the size or length of each individual dimension.

In [1]:
import numpy as np

In [2]:
x_4d = np.array([
    [
     [[1], [2]],
     [[3], [4]],
     [[5], [6]]
    ],

    [[[7], [8]], [[9], [10]], [[11], [12]]],
    
    [[[13], [14]], [[15], [16]], [[17], [18]]],
    
    [[[19], [20]], [[21], [22]], [[23], [24]]]
])

In [61]:
x_4d.ndim

4

In [62]:
np.ndim(x_4d)

4

In [5]:
x_4d.shape

(4, 3, 2, 1)

In [6]:
np.shape(x_4d)

(4, 3, 2, 1)

In [49]:
x_4d.dtype

dtype('int64')

In [50]:
type(x_4d)

numpy.ndarray

In [7]:
x_3d = np.array([
    [
     [1, 2], 
     [3, 4], 
     [5, 6]
    ], 
    [[7, 8], [9, 10], [11, 12]],
    [[13, 14], [15, 16], [17, 18]],
    [[19, 20], [21, 22], [23, 24]]
])

In [8]:
x_3d.ndim

3

In [9]:
x_3d.shape

(4, 3, 2)

In [52]:
y_3d = np.array([
    [[1], [2]],
    [[3], [4]],
    [[5], [6]],
    [[7], [8]]
], dtype = np.int16)

In [53]:
y_3d.ndim

3

In [54]:
y_3d.shape

(4, 2, 1)

In [55]:
y_3d.dtype

dtype('int16')

In [56]:
y_2d = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
], dtype=np.float32)

In [57]:
y_2d.ndim

2

In [58]:
y_2d.shape

(4, 2)

In [59]:
y_2d.dtype

dtype('float32')

In [20]:
z_2d = np.array([
    [1],
    [2],
    [3]
])

In [21]:
z_2d.ndim

2

In [22]:
z_2d.shape

(3, 1)

In [23]:
z_1d = np.array([
    1, 2, 3
])

In [24]:
z_1d.ndim

1

In [25]:
z_1d.shape

(3,)

## `np.random.randn()` function

The `np.random.randn()` function in Python's NumPy library returns a sample or samples from the standard normal distribution (mean 0, variance 1).

In [26]:
# Return a single random float
np.random.randn()

-0.08223178940613222

In [28]:
# Return a 1D array of random floats
np.random.randn(5)

array([-0.62388179, -0.28258786, -0.78793884,  2.24726771, -1.7948243 ])

In [31]:
# Return a 2D array (matrix) of random floats
np.random.randn(3, 4)

array([[-0.03050466, -0.00567741,  0.09928976,  0.12939438],
       [-1.2841636 , -0.55282222, -0.74818068, -0.63557122],
       [-0.15278241,  0.0162129 , -0.85512228,  0.05135441]])

In [33]:
# Return a 3D array (tensor) of random floats
np.random.randn(3, 2, 1)

array([[[-1.09475595],
        [ 0.10697211]],

       [[ 2.45883065],
        [ 1.15016355]],

       [[-0.55067807],
        [ 0.04480969]]])

In [43]:
sizes = [10, 5, 3]

In [44]:
biases = [np.random.randn(size, 1) for size in sizes[1:]]
biases

[array([[-1.43037703],
        [-0.79677137],
        [-0.88001574],
        [ 1.3305554 ],
        [ 0.51244541]]),
 array([[-0.90231035],
        [-0.23910166],
        [ 0.89785951]])]

In [45]:
sizes = [3, 2, 1]

In [48]:
weights = [np.random.rand(next, curr) for curr, next in zip(sizes[:-1], sizes[1:])]
weights

[array([[0.63635649, 0.56577453, 0.62712449],
        [0.77667971, 0.76287705, 0.54005721]]),
 array([[0.01355578, 0.79827431]])]